baseURL = "https://blog.smilesion.xyz/"
languageCode = "zh-cn"
title = "SmileSion's Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  hidePoweredBy = true 

[params.assets]
  favicon = "/favicon.ico"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false

