baseURL = "https://smilesion.github.io/SionBlog/"
languageCode = "zh-cn"
title = "Sion's Tech Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true

