baseURL = "https://blog.smilesion.xyz/"
languageCode = "zh-cn"
title = "SmileSion's Blog"
theme = "PaperMod"
copyright = "© 2026 SmileSion · All rights reserved"
enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowToc = true          # 显示文章目录

[params.cover]
  linkFullImages = false      # 点击图片是否查看原图
  responsiveImages = true    # 是否开启响应式图片（需 Hugo Extended 版本）

[params.profileMode]
  enabled = true
  title = "Welcome to SmileSion's Blog!"
  subtitle = "Smile.Rules.Consequeces."
  imageUrl = "/images/avatar.png"
  imageTitle = "SmileSion"
  imageWidth = 120
  imageHeight = 120

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/SmileSion"

[[params.socialIcons]]
  name = "email"
  url = "mailto:1065716478@qq.com"

[[params.socialIcons]]
  name = "qq"
  url = "https://qm.qq.com/q/9zQYugIWcM"

[[params.socialIcons]]
  name = "steam"
  url = "https://steamcommunity.com/id/SmileSion/"

[params.assets]
  favicon = "/favicon.ico"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = false

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 5

  [[menu.main]]
    name = "Photos"
    # url = "https://500px.com.cn/SmileSion"
    url = "/photos/"
    weight = 3

[markup.goldmark.renderer]
    unsafe = true  # 允许在 Markdown 中使用 HTML 代码

[outputs]
home = ["HTML", "RSS", "JSON"]
